name: Release
on:
  release:
    types:
      - created

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: publish
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Create artifacts
        run: npm run make
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: out/downloads/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
